
swagger: "2.0"
info:
  version: "1.0.0"
  title: "recipes"
basePath: "/api/v1"
tags:
  - name: "recipes"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /recipes:
    get:
      tags:
      - "recipes"
      summary: "Get all recipes"
      operationId: "get_recipes"
      responses:
        200:
          description: "Successfully retrieved recipes"
          schema:
            $ref: "#/definitions/recipe"
        404:
          description: "recipe doesn't exist"
      x-swagger-router-controller: "recipes_api.web.controllers.recipe_controller"
  /recipe:
    post:
      tags:
      - "recipe"
      summary: "create new recipe"
      operationId: "post_recipe"
      parameters:
        - name: "request_body"
          in: "body"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/new_recipe"
      responses:
        200:
          description: "Successfully created new recipe"
          schema:
            $ref: "#/definitions/recipe"
        404:
          description: "recipe doesn't exist"
      x-swagger-router-controller: "recipes_api.web.controllers.recipe_controller"
  /recipe/{recipe_id}:
    put:
      tags:
      - "recipe"
      summary: "update recipe data in database"
      operationId: "put_recipe"
      parameters:
        - name: "recipe_id"
          in: "path"
          description: "The id of the recipe to update"
          required: true
          type: "string"
        - name: "request_body"
          in: "body"
          required: true
          schema:
            $ref:  "#/definitions/new_recipe"
      responses:
        200:
          description: "Successfully retrieved recipe"
          schema:
            $ref: "#/definitions/recipe"
        404:
          description: "recipe doesn't exist"
      x-swagger-router-controller: "recipes_api.web.controllers.recipe_controller"
    get:
      tags:
      - "recipe"
      summary: "Get recipe from database"
      operationId: "get_recipe"
      parameters:
        - name: "recipe_id"
          in: "path"
          description: "The id of the recipe to retrieve"
          required: true
          type: "string"
      responses:
        200:
          description: "Successfully retrieved recipe"
          schema:
            $ref: "#/definitions/recipe"
        404:
          description: "recipe doesn't exist"
      x-swagger-router-controller: "recipes_api.web.controllers.recipe_controller"
    delete:
      tags:
      - "recipe"
      summary: "Remove a recipe from the database"
      operationId: "delete_recipe"
      parameters:
        - name: "recipe_id"
          in: "path"
          description: "The id of the recipe to delete"
          required: true
          type: "string"
      responses:
        202:
          description: "Successfully deleted recipe"
        404:
          description: "recipe doesn't exist"
      x-swagger-router-controller: "recipes_api.web.controllers.recipe_controller"
definitions:
  new_recipe:
    required:
    - recipe_name
    - recipe_description
    - recipe_ingredients
    - recipe_directions
    - recipe_tags
    properties:
      recipe_name:
        type: string
      recipe_description:
        type: string
      recipe_ingredients:
        type: array
        items:
          type: object
          properties:
            ingridient_name:
              type: string
            measurement:
              type: string
      recipe_directions:
        type: array
        items:
          type: object
          properties:
            step_order:
              type: integer
            step_directions:
              type: string
      recipe_tags:
        type: array
        items:
          type: string

  recipe:
    properties:
      id:
        type: object
        properties:
          recipe_name:
            type: string
          recipe_description:
            type: string
          recipe_ingredients:
            type: array
            items:
              type: object
              properties:
                ingridient_name:
                  type: string
                measurement:
                  type: string
          recipe_directions:
            type: array
            items:
              type: object
              properties:
                step_order:
                  type: integer
                step_directions:
                  type: string
          recipe_tags:
            type: array
            items:
              type: string

...